PROGRAM = do_op

OUT = do-op

SRC = main.c operations.c

all: $(PROGRAM)

$(PROGRAM):
		gcc -Wall -Wextra -Werror $(SRC) -o $(OUT)

clean:
		/bin/rm -f $(OUT)

fclean: clean
		/bin/rm -f $(OUT)

re: fclean all

















